#!/usr/bin/env bash
#secure copy of local file to server
#Takes 4 params
#1st param is path to file
#2nd param is IP
#3rd param is user name
#4th param is path to private key

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi

