#!/usr/bin/env bash

# Update package list and install nginx
apt-get update -y
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:80;/g' /etc/nginx/sites-available/default

service nginx restart

