#!/usr/bin/env bash
#add redirection page
apt-get update -y
apt-get install -y nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

sed -i 's|root /var/www/html;|root /etc/nginx/html;|g' /etc/nginx/sites-available/default

echo "
server {
    listen 80;
    listen [::]:80;

    root /etc/nginx/html;
    index index.html;

    server_name localhost;

    # Redirection for /redirect_me
    location /redirect_me {
        return 301 https://www.youtube.com;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
" > /etc/nginx/sites-available/default

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:80;/g' /etc/nginx/sites-available/default

service nginx restart

