#!/usr/bin/env bash
# return 404 not fount page
apt-get update -y
apt-get install -y nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/404.html

echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

sed -i 's|root /var/www/html;|root /etc/nginx/html;|g' /etc/nginx/sites-available/default

echo "
server {
    listen 80;
    listen [::]:80;

    root /etc/nginx/html;
    index index.html;

    server_name localhost;

    # Custom 404 error page
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
" > /etc/nginx/sites-available/default

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:80;/g' /etc/nginx/sites-available/default

service nginx restart

