#!/usr/bin/env bash
# This script configures nginx with a custom HTTP header

apt-get update -y
apt-get install -y nginx

HOSTNAME=$(hostname)

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By "$HOSTNAME";
    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

service nginx restart
