#!/usr/bin/env bash
#This script prints best school 

i=0
while [ $i -lt 10 ];
do
 if [ $i == 4 ]; then
	 echo "bad luck"
 elif [ $i == 8 ]; then
	 echo "good luck"
 else 
	 echo "Best School"
 fi
 (( i++ ))
done
