#!/usr/bin/env bash
#This script printsfrom 1 to 20

i=0
while [ $i -lt 21 ];
do
 case $i in
	 4)
		 echo "bad luck from China"
		 ;;
	 9)
		 echo "bad luck from Japan"
		 ;;
	 17)
	 	echo "bad luck from Italy"
		;;
	*)
		echo "$i"
 esac
 (( i++ ))
done
